### PR TITLE
#455 Make clear only MetaMask L2

### PR DESCRIPTION
**Pull request by Boda805**
Styling of text on L2 page could be better but this should do the trick

### CODE REVIEW

**Comment by clementbalestrat** [comment]
@Boda805 can you please describe what your PR does? I had a look at the code and I'm a bit confused on what you are trying to achieve here?

**Comment by Boda805** [comment]
It's to answer issue #455 to dim out options for L2 when a wallet other than MetaMask is selected, as it's stated on the issue that MetaMask is only wallet supported for L2. I probably should have done a draft as some of it is a little crude yet but let me know what you think.

**Comment by clementbalestrat** [comment]
@Boda805 Thanks! I'll try to have a look at it today or tomorrow.

**Review by JChiaramonte7 — CHANGES_REQUESTED** [review]
Hey @Boda805 thanks for the PR. Currently discussing with @drptbl on #455, but I don't think we need this because we already have a pretty strong disclaimer. 

Also could you regenerate your lockfile with npm 6? We haven't switched to 7 yet, but we'll probably do this in a separate PR.

**Comment by clementbalestrat** [comment]
Closing that one for now until we decide what to do.

**Pull request closed without merging**
