### PR TITLE
Implement hedging indicator

### PR DESCRIPTION
**Pull request by mi-yu**
Addresses this [tweet](https://twitter.com/kaiynne/status/1357807384379281408) and #305 (point 3) by showing a hedging indicator/warning when user's synth holdings distribution deviates from the global debt pool's distribution. I believe this is different from what the tweet was describing and more closely follows the github issue.

Some further questions/considerations:

- the logic for showing warnings is based on a hedging strategy of just mirroring the global distribution of the debt pool, is the goal of a hedging indicator to encourage this strategy? What other hedging strategies exist?
- the threshold for triggering the indicator as well as the wording are mostly placeholders for now, would definitely appreciate input on this

Here's an example of the indicator for wallet `0x2BDE3b9C0129be4689E245Ba689b9b0Ae4AC666D`

image

### CODE REVIEW

**Comment by clementbalestrat** [comment]
@mi-yu Thanks! I will have a look at it tomorrow :)

**Comment by mi-yu** [comment]
Thank you!

**Comment by dvd-schwrtz** [comment]
@mi-yu I will be the one to take a look actually. Probably tomorrow. From a brief glance at the code it looks like you did a good job. Will post some feedback for your PR tomorrow most likely :)

**Comment by mi-yu** [comment]
@dvd-schwrtz hi just wondering if you had a chance to look at this, or if you have any high level comments about the approach

**Comment by dvd-schwrtz** [comment]
Sorry, @mi-yu was slammed for a few days with a new feature. @clementbalestrat is going to take a look at this over the weekend. Thanks for your patience.

**Comment by clementbalestrat** [comment]
@mi-yu the code looks good! Now we're currently discussing internally what is the best way to display this information. I'm afraid the little warning icon might be a bit confusing for some users.

I'll get back to you as soon as possible.

**Comment by mi-yu** [comment]
I agree the warning symbol is confusing especially for newer users, an alternative I've been thinking about is some sort of toggleable side by side comparison of debt pool holdings vs user's holdings

I'll wait for discussion to wrap up before continuing though!

**Comment by clementbalestrat** [comment]
Hey @mi-yu! Thanks for your patience, here is what our designer suggested: 
Screen Shot 2021-02-17 at 9 18 26 pm

**Comment by clementbalestrat** [comment]
So the idea is to move the logic to the "debt" page, and below the debt chart, add two kind of info:
- One pie chart representing the synth dominance (same as on https://stats.synthetix.io/#synths)
- A table with all the synths and a comparison in % with the debt pool. Green if <=5% difference, red if > 5%.

Do you think you would be able do that? Don't spend too much time on the design, I can finish it as I know the codebase pretty well and will be able to reuse the existing components.

Ping me if you have some questions :)

**Comment by mi-yu** [comment]
Hi, I can work on this today, thanks for the design guidelines!

**Comment by clementbalestrat** [comment]
Thanks @mi-yu!

**Comment by mi-yu** [comment]
hi @clementbalestrat just pushed an implementation of the debt pie chart + portfolio hedging indicator. The diff is big right now since I rebased on top of the dev branch, but I believe the target branch for the PR is stale, so a merge/rebase on that branch will clean things up a bit!

Also, some styling doesn't quite match designs yet, but wanted to get some feedback on how I reused the `AssetsTable` component for the hedging indicator. Not sure if adding more props to customize the layout is the way to go, or if its preferred to just make a new component.

Here's what it looks like now:
image

**Comment by clementbalestrat** [comment]
Thanks so much @mi-yu! Will review it tomorrow 🙂

**Pull request merged**
