### PR TITLE
feat: ens name support

### PR DESCRIPTION
**Pull request by sasicodes**
image

### CODE REVIEW

**Comment by fritzschoff** [comment]
Looking good, though it will fail if user is on L2. Is this PR handling that case?

**Comment by sasicodes** [comment]
@fritzschoff If no ensName is found( in the case of other networks), it fallbacks to show the truncated user address.

**Comment by fritzschoff** [comment]
Awesome. Can you resolve the conflicts so we can merge it :)

**Comment by sasicodes** [comment]
@fritzschoff Resolved conflicts

**Review by fritzschoff — APPROVED** [review]

**Comment by fritzschoff** [comment]
Awesome. Thank you so much!

**Review by fritzschoff — APPROVED** [review]

**Pull request merged**
