### PR TITLE
Create C-ratio progress bar

### PR DESCRIPTION
**Pull request by 0xjocke**
https://staking-storybook-git-c-ratio-progress-bar-synthetixio.vercel.app/?path=/story/cratioprogressbar--primary
Screen Shot 2022-08-29 at 10 12 53 pm
Screen Shot 2022-08-29 at 10 01 20 pm
Screen Shot 2022-08-29 at 10 01 11 pm
https://staking-storybook-git-banner-synthetixio.vercel.app/

### CODE REVIEW

**Comment by jmzwar** [comment]
Looks good - we could probably replace box with the [progress component](https://chakra-ui.com/docs/components/progress/usage) that Chakra exposes:

**Comment by bachstatter** [comment]
> Looks good - we could probably replace box with the [progress component](https://chakra-ui.com/docs/components/progress/usage) that Chakra exposes:

ah missed that one. yep definitely. Was fun doing some data vis been too long hehe

**Review by noisekit — APPROVED** [review]

**Review by noisekit — APPROVED** [review]
Looks good to me. Suggestions are optional as usual

**Review by jmzwar — APPROVED** [review]
Looks good - let's start to get these in front of designers :)

**Pull request merged**
