### PR TITLE
fix: mobile network switch issue

### PR DESCRIPTION
**Pull request by vbstreetz**

### CODE REVIEW

**Comment by vbstreetz** [comment]
Seems the detected `provider` has undefined values for some reason on reload 🤔 

Screenshot 2021-05-28 at 23 08 39

**Comment by vbstreetz** [comment]
Logged the issue here https://github.com/MetaMask/metamask-mobile/issues/2732. Although, it might be nextjs related..

**Comment by vbstreetz** [comment]
Issue is affecting kwenta as well..

**Comment by clementbalestrat** [comment]
@vbstreetz closing this one for now.

**Pull request closed without merging**
