### PR TITLE
port of Mintr debt tracking ui to Staking

### PR DESCRIPTION
**Pull request by rockefeller92**
Revised my original PR to focus just on the debt tracking UI - seems like further coordination is needed to determine how and where this should be integrated with the rest of the UI.

All components are properly typed .tsx, new debt snapshot query follows existing query model.

New icon included to match new icon style
Chart and table restyled to match new UI

Capture

Demo video here:

https://user-images.githubusercontent.com/78625401/107164785-55fa1c00-6965-11eb-937f-372ef52d6273.mp4

..working on getting a live demo on heroku..

### CODE REVIEW

**Comment by clementbalestrat** [comment]
@rockefeller92 thanks! having a look at it now :)

**Comment by clementbalestrat** [comment]
@rockefeller92 thanks for your PR! Unfortunately we decided to merge another one which we thought had a UI and codebase closer to what's already on Staking. But send me a ETH address and we will send you a small reward to compensate the time you spent working on this.

**Comment by rockefeller92** [comment]
Thanks @clementbalestrat you can send here: 0x1aeBB247afa3DAb8e115c5B13392f18DB64ff052

**Comment by clementbalestrat** [comment]
@rockefeller92 Thanks. Will take care of it today or tomorrow!

**Pull request closed without merging**
