### PR TITLE
browser wallet added

### PR DESCRIPTION
**Pull request by clementbalestrat**
This PR:

- Adds browser wallet support (any wallet which injects window.ethereum) such as Metamask, Frame.sh...etc
- Fixes the Input colour when selecting a wallet address for Ledger & Trezor.
- Updates the "please-install-metamask" copy

### CODE REVIEW

**Review by andytcf — APPROVED** [review]
LGTM

**Comment by andytcf** [comment]
@drptbl only workflow that seems to be broken from my quick QA is connecting directly using a ledger nano x

**Comment by drptbl** [comment]
@clementbalestrat e2e tests were failing because of these changes, I've updated them for you.

**Review by evgenyboxer — APPROVED** [review]
lgtm!

**Pull request merged**
